server:
  port: 8080

spring:
  application:
    name: kotlin-hello

db:
  datasource:
    driver-class-name: org.postgresql.Driver
    pool-name: epayment-kz-pool
    max-pool-size: 20
    connection-timeout: 15000
    validation-timeout: 10000
    idle-timeout: 30000
    min-idle: 5
    username: postgres
    password: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/test

flyway:
  url: ${db.datasource.jdbc-url}
  schemas: public
  user: ${db.datasource.username}
  password: ${db.datasource.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    version: 1.0

springdoc:
  servers: http://localhost:${server.port}